""" Encode any known changes to the database here
to help the matching process
"""

# Renamed modules is a mapping from old module name to new module name
renamed_modules = {
    # odoo
    "l10n_es_pos_tbai": "l10n_es_edi_tbai_pos",
    "mrp_subonctracting_landed_costs": "mrp_subcontracting_landed_costs",
    "website_sale_picking": "website_sale_collect",
    "website_form_project": "website_project",
    # odoo/enterprise
    # OCA/commission
    "account_commission": "account_commission_oca",
    "commission": "commission_oca",
    "sale_commission": "sale_commission_oca",
    # OCA/product-attribute
    "product_packaging_type_vendor": "product_packaging_level_vendor",
    "product_supplierinfo_for_customer": "product_customerinfo",
    "product_template_tags_code": "product_tags_code",
    "stock_packaging_calculator": "product_packaging_calculator",
    # OCA/project
    "project_stock": "project_task_stock",
    "project_stock_product_set": "project_task_stock_product_set",
    # OCA/sale-promotion
    "coupon_chatter": "loyalty_program_chatter",
    # OCA/sale-workflow
    "product_supplierinfo_for_customer_sale": "product_customerinfo_sale",
    "sale_product_set_sale_by_packaging": "product_set_sell_only_by_packaging",
    # OCA/stock-logistics-workflow
    "stock_picking_type_shipping_policy": "stock_picking_type_force_move_type",
    # OCA/web
    "web_widget_product_label_section_and_note": "web_widget_product_label_section_and_note_name_visibility",  # noqa: E501
    # OCA/...
}

# Merged modules contain a mapping from old module names to other,
# preexisting module names
merged_modules = {
    # odoo
    "account_audit_trail": "account",
    "account_lock": "account",
    "account_payment_term": "account",
    "l10n_br_pix": "l10n_br",
    "l10n_de_audit_trail": "l10n_de",
    "l10n_dk_audit_trail": "l10n_dk",
    "l10n_dk_bookkeeping": "account",
    "l10n_es_edi_facturae_adm_centers": "l10n_es_edi_facturae",
    "l10n_es_edi_facturae_invoice_period": "l10n_es_edi_facturae",
    "l10n_es_edi_tbai_multi_refund": "l10n_es_edi_tbai",
    "l10n_fr_fec": "l10n_fr_account",
    "l10n_fr_invoice_addr": "l10n_fr_account",
    "l10n_ro_efactura": "l10n_ro_edi",
    "im_livechat_mail_bot": "mail_bot",
    "payment_ogone": "payment_worldline",
    "payment_sips": "payment_worldline",
    "pos_sale_product_configurator": "pos_sale",
    "sale_product_configurator": "sale",
    "stock_landed_costs_company": "stock_landed_costs",
    "website_sale_product_configurator": "website_sale",
    # odoo/enterprise
    # OCA/knowledge
    "document_page_group": "document_page_access_group",
    # OCA/l10n-france
    "l10n_fr_pos_cert_update_draft_order_line": "l10n_fr_pos_cert",
    # OCA/sale-workflow
    "sale_order_qty_change_no_recompute": "sale",
    # OCA/...
}

# only used here for upgrade_analysis
renamed_models = {
    # odoo
    "hr.applicant.skill": "hr.candidate.skill",
    "l10n_es_edi_facturae_adm_centers.ac_role_type": ""
    "l10n_es_edi_facturae.ac_role_type",
    "mail.notification.web.push": "mail.push",
    "mail.partner.device": "mail.push.device",
    "mail.shortcode": "mail.canned.response",
    "pos.combo": "product.combo",
    "pos.combo.line": "product.combo.item",
    # OCA/...
}

# only used here for upgrade_analysis
merged_models = {
    # odoo
    "google.calendar.credentials": "res.users.settings",
    "l10n_es_edi_facturae.certificate": "certificate.certificate",
    "l10n_es_edi.certificate": "certificate.certificate",
    "microsoft.calendar.credentials": "res.users.settings",
    "mrp.document": "product.document",
    # OCA/...
}

# List of OCA modules that were moved to other repositories .
# Format: {"module_name": ("old_repo_name", "new_repo_name")}
# Note: The key is the module_name for easier reference
moved_modules = {
    # OCA/social
    "base_search_mail_content": ("social", "mail"),
    "mail_activity_board": ("social", "mail"),
    "mail_activity_done": ("social", "mail"),
    "mail_activity_team": ("social", "mail"),
    "mail_attach_existing_attachment": ("social", "mail"),
    "mail_attach_existing_attachment_account": ("social", "mail"),
    "mail_autogenerated_header": ("social", "mail"),
    "mail_autosubscribe": ("social", "mail"),
    "mail_composer_cc_bcc": ("social", "mail"),
    "mail_inline_css": ("social", "mail"),
    "mail_layout_preview": ("social", "mail"),
    "mail_message_search": ("social", "mail"),
    "mail_notification_clean_status_error": ("social", "mail"),
    "mail_notification_custom_subject": ("social", "mail"),
    "mail_outbound_static": ("social", "mail"),
    "mail_partner_forwarding": ("social", "mail"),
    "mail_quoted_reply": ("social", "mail"),
    "mail_restrict_follower_selection": ("social", "mail"),
    "mail_send_confirmation": ("social", "mail"),
    "mail_show_follower": ("social", "mail"),
    "mail_tracking": ("social", "mail"),
    "mail_tracking_mailgun": ("social", "mail"),
    "mail_tracking_mass_mailing": ("social", "mail"),
    # OCA/server-ux
    "mail_suggested_recipient_unchecked": ("server-ux", "mail"),
}
